Add missing jaxb-api dependency
jaxb-api dependency is needed to be able to build and run the clamav-rest
with Java 11 since it no longer includes javax.xml.bind.* and results in e.g.

java.lang.ClassNotFoundException: javax.xml.bind.ValidationException